{{- if and .Values.ingress.enabled .Values.ingress.domain }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "accessible-pdf.fullname" . }}
  annotations:
    {{- if .Values.ingress.clusterIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer }}
    {{- end }}
spec:
  ingressClassName: traefik
  rules:
    - host: {{ .Values.ingress.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "accessible-pdf.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
  tls:
    - hosts:
        - {{ .Values.ingress.domain }}
      secretName: {{ printf "%s-tls" (include "accessible-pdf.fullname" .) }}
{{- end }}
